name: Sync Upstream

permissions: write-all

on:
  workflow_dispatch:
      inputs:
        Lineage-21:
          required: true
          type: boolean
          default: true
        Unofflineage-21:
          required: true
          type: boolean
          default: true
        Lineage-21-beta:
          required: true
          type: boolean
          default: true
        CrDroid:
          required: true
          type: boolean
          default: true
        Sleepy:
          required: true
          type: boolean
          default: true
        PixelOS:
          required: true
          type: boolean
          default: true
        DerpFest:
          required: true
          type: boolean
          default: true


jobs:
  sync-upstream-lineage21:
    if: ${{ inputs.Lineage-21 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: los21
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: xiaomi-sm6150/android_kernel_xiaomi_sm6150
          upstream-branch: lineage-21
          branch: los21

  sync-upstream-unofflineage21:
    if: ${{ inputs.Unofflineage-21 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: unofflos21
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: raul-16/android_kernel_xiaomi_davinci
          upstream-branch: lineage-21
          branch: unofflos21

  sync-upstream-lineage21-beta:
    if: ${{ inputs.Lineage-21-beta }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: lineage-21
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: basamaryan/android_kernel_xiaomi_sm6150
          upstream-branch: lineage-21
          branch: lineage-21
          
  sync-upstream-crdroid14:
    if: ${{ inputs.CrDroid }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: crdroid14
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: crdroidandroid/android_kernel_xiaomi_sm6150
          upstream-branch: "14.0"
          branch: crdroid14

  sync-upstream-sleepy:
    if: ${{ inputs.Sleepy }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: sleepy
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: itsshashanksp/kernel_xiaomi_sm6150
          upstream-branch: sleepy-inline
          branch: sleepy

  sync-upstream-pixelos:
    if: ${{ inputs.PixelOS }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: pos14
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: PixelOS-Devices/kernel_xiaomi_sm6150
          upstream-branch: fourteen
          branch: pos14

  sync-upstream-derpfest:
    if: ${{ inputs.DerpFest }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: derp14
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: DerpFest-Devices/kernel_xiaomi_sm6150
          upstream-branch: 14
          branch: derp14
